version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: engineering-hub-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build: ./backend
    container_name: engineering-hub-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./chat_histories:/app/chat_histories
      - ./mock_disk:/app/mock_disk
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: engineering-hub-frontend
    depends_on:
      - backend
    volumes:
      # ЭТА СТРОКА - КЛЮЧЕВОЕ ИСПРАВЛЕНИЕ.
      # Мы говорим контейнеру frontend использовать наш правильный nginx.conf
      # вместо его дефолтного.
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build: ./nginx
    container_name: engineering-hub-nginx
    # Мы больше не используем кастомный конфиг здесь,
    # так как теперь вся маршрутизация происходит в системном Nginx.
    # Но мы оставляем сервис как точку входа.
    # ВАЖНО: Мы удаляем старый volume из этого сервиса.
    depends_on:
      - frontend
    ports:
      - "8081:80"
    volumes:
      - /etc/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
