# docker-compose.yml

version: '3.8'

services:
  # Nginx remains the same
  nginx:
    container_name: engineering-hub-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  # Frontend remains the same
  frontend:
    container_name: engineering-hub-frontend
    build: ./frontend
    restart: unless-stopped

  # Backend gets modified
  backend:
    container_name: engineering-hub-backend
    build: ./backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./backend:/app
    depends_on:
      - redis # NEW DEPENDENCY

  # NEW SERVICE: Redis
  redis:
    container_name: engineering-hub-redis
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  # NEW SERVICE: Worker
  worker:
    container_name: engineering-hub-worker
    build: ./worker # It will have its own Dockerfile
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./worker:/app
      - ./backend/kb_service:/app/kb_service # Share the knowledge base service code
    depends_on:
      - redis
