version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: engineering-hub-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: engineering-hub-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    volumes:
      - ./backend:/app
    ports:
      - "127.0.0.1:8888:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: engineering-hub-frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "127.0.0.1:3333:3000"
    restart: unless-stopped

volumes:
  postgres_data:
